version: "3.8"
services:
  backend: # 배포용
    build: .
    container_name: yeogigangwon-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start

  mongo: #
    image: mongo:5.0
    container_name: yeogigangwon-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sdsqkqh!
    command: 
      - "--noauth"  # 인증 비활성화

  python-api:
    build: ./python-api
    container_name: yeogigangwon-python-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data:
